Added check for downloadin nasm
StormSurgeLive/asgs pull request #1061
Opened 2022-12-30 17:24 UTC by jasonfleming

resolves #1060

2023-01-05 04:04 UTC, wwlwpd requested changes
Check out the change suggestion I made, if good you should be able to directly accept / apply it from here.

2023-01-05 04:04 UTC, wwlwpd commented on cloud/general/init-ffmpeg.sh
> +if [[ -e ${NASM_TGZ} && -s ${NASM_TGZ} &&  "$(file nasm-2.15.05.tar.gz)" =~ "gzip compressed data" ]]; then
```suggestion
if [[ -e ${NASM_TGZ} && -s ${NASM_TGZ} &&  "$(file ${NASM_TGZ} )" =~ "gzip compressed data" ]]; then
```

2023-01-05 04:04 UTC, wwlwpd commented on cloud/general/init-ffmpeg.sh
> +if [[ -e ${NASM_TGZ} && -s ${NASM_TGZ} &&  "$(file nasm-2.15.05.tar.gz)" =~ "gzip compressed data" ]]; then
Did you mean this? Also, checkout we can suggest smallish fixes in the code review itselft, neat!

(press this button to do so, ![image](https://user-images.githubusercontent.com/46434714/210699382-fc7300fa-66e7-4d96-b613-1c38d599b19b.png))

2023-01-05 12:29 UTC, jasonfleming commented
Thank you for that fix @wwlwpd, not sure how the literal file name got in there, I must have cut and pasted it. :-)

2023-01-05 12:29 UTC, jasonfleming commented
I agree the PR fix inline suggest/commit mechanism is a productivity booster!

2023-01-08 15:14 UTC, jasonfleming commented
I think this is ready to go.

2023-01-10 09:39 UTC, wwlwpd approved these changes

2023-01-10 09:41 UTC, merged