Changes to support AGT
StormSurgeLive/asgs pull request #1068
Opened 2023-01-07 20:06 UTC by jasonfleming

resolves #1063 ... will let it run for a few days before lifting "draft" status

2023-01-08 15:36 UTC, jasonfleming commented
@wwlwpd when I made this PR, GitHub flagged a conflict with master in `config/forcing_defaults.sh` and I resolved it through the GItHub site directly. May not have been a good idea, since it seems that GH merged changes to `master` into the `issue-1063` branch, which is not our usual workflow. Does this merge need to be undone? Please let me know if I need to fix it.

2023-01-27 15:46 UTC, wwlwpd requested changes
Minor change, please accept. otherwise looks good. I can squash and merge. Please confirm. TY!

2023-01-27 15:46 UTC, wwlwpd commented on asgs_main.sh
> +            curl ${LOADTIDEURL}/${FNAME}.xz > ${FPATH}/${FNAME}.xz 2> errmsg || warn "$THIS: Failed to download file from ${LOADTIDEURL}/${FNAME}.xz to ${FPATH}/${FNAME}.xz: `cat errmsg`."
```suggestion
           curl ${LOADTIDEURL}/${FNAME}.xz > ${FPATH}/${FNAME}.xz 2> errmsg || warn "$THIS: Failed to download file from ${LOADTIDEURL}/${FNAME}.xz to ${FPATH}/${FNAME}.xz: `cat errmsg`."
```

2023-01-27 15:49 UTC, jasonfleming commented on asgs_main.sh
> +            curl ${LOADTIDEURL}/${FNAME}.xz > ${FPATH}/${FNAME}.xz 2> errmsg || warn "$THIS: Failed to download file from ${LOADTIDEURL}/${FNAME}.xz to ${FPATH}/${FNAME}.xz: `cat errmsg`."
Yes I accept! :-)

2023-01-27 15:53 UTC, wwlwpd approved these changes

2023-01-27 16:27 UTC, closed without merging