Added scripts and test data for json and yaml support.
StormSurgeLive/asgs pull request #497
Opened 2021-05-18 18:14 UTC by jasonfleming

resolves #496

2021-05-19 18:02 UTC, wwlwpd requested changes
see code comments

2021-05-19 18:02 UTC, wwlwpd commented on util/input/meteorology/read_json.pl
> +sub stderrMessage () {
yeah definitely put this in a module, maybe `./PERL/ASGS/Logger.pm` (i.e., `use ASGS::Logger`) - `$SCRIPTDIR/PERL` is already in `PERL5LIB`, so new custom modules just need to go in there.

2021-05-31 09:53 UTC, wwlwpd commented
@jasonfleming upon further review, this PR really looks like it was not fully completed. When you get a chance, please make sure the files being added in this branch are working as intended. I can't see how they are, especially `deserialize.pl` which won't even compile under `perl` for a variety of reasons.

2021-05-31 09:57 UTC, wwlwpd requested changes
@jasonfleming I need you to review this PR and tell me if it's incomplete. I can't guess what it is you want to do in some cases; also:

* `deserialize.pl` won't compile (see comments)
* `read_json.pl` also looks incomplete (e.g., it has `use YAML::Tiny;`)

2021-05-31 09:57 UTC, wwlwpd commented on util/input/meteorology/deserialize.pl
> +if ( $type eq "json" ) {
`$type` is never defined.

2021-06-02 14:00 UTC, jasonfleming commented
@wwlwpd sorry for the confusion, I will fix these issues.

2021-06-02 17:11 UTC, jasonfleming commented
Hey @wwlwpd sorry about this PR, I started work on it in March and then set it aside. When I came back to it, I did not pick up where I left off correctly. These scripts and test files were experimental, and I had forgotten that. We do not need to move forward with these, so I am closing this PR. Thank you for reviewing this.

2021-06-02 17:11 UTC, closed without merging