Improvements to download NAM files for tc-forced nowcasts.
StormSurgeLive/asgs pull request #655
Opened 2021-09-22 19:21 UTC by jasonfleming

resolves #654

2021-09-24 20:43 UTC, wwlwpd requested changes
see comments

2021-09-24 20:43 UTC, wwlwpd commented on asgs_main.sh
> +            if [[ $BACKGROUNDMET != "namBlend" ]]; then
I think we need to prefer managing these as `case/esac` just to plan for growth.  Also, checking a _negative_ (e.g., `!= "namBlend")` is asking for trouble, let's make this more positive :) - and `case/esac`.

2021-09-24 20:43 UTC, wwlwpd commented on asgs_main.sh
> +      if [[ $BACKGROUNDMET == "namBlend" && $BASENWS -gt 8 ]]; then
let's do this as a `case/esac`

2021-09-25 13:44 UTC, jasonfleming commented on asgs_main.sh
> +      if [[ $BACKGROUNDMET == "namBlend" && $BASENWS -gt 8 ]]; then
Excellent, can do. Thank you.

2021-09-25 16:21 UTC, jasonfleming commented
I replaced the if/thens with case/esacs along with logging and reliability improvements. Have not tested yet.

2021-09-26 07:41 UTC, wwlwpd commented
Looks *a lot* better! I didn't see any logical or syntax issues with it, but let me know how you'd like to proceed with testing; and I can help. Otherwise, let me know that it's working as you expected and I'll approve it and merge it.

2021-09-30 08:26 UTC, wwlwpd approved these changes

2021-09-30 08:27 UTC, wwlwpd commented
@jasonfleming feel free to merge this once you're convinced it's working as expected - looks good to me, but I'll defer to you

2021-10-01 14:23 UTC, merged