Added files to support URIv18 mesh
StormSurgeLive/asgs pull request #910
Opened 2022-07-10 15:04 UTC by jasonfleming

resolves #860

2022-07-11 01:54 UTC, wwlwpd commented on config/mesh_defaults.sh
> +"uriv18"|"URIv18")
I think we're missing here:
```
nodes=...
elements=...
```

2022-07-11 01:55 UTC, wwlwpd commented on config/mesh_defaults.sh
> +      INPUTDIR=$SCRIPTDIR/input/meshes/hsofs_NE-hires_v2_depf2
missing, `elements` and `nodes`

2022-07-11 01:56 UTC, wwlwpd requested changes
missing element and node fields for both meshes

2022-07-11 09:33 UTC, jasonfleming commented on config/mesh_defaults.sh
> +"uriv18"|"URIv18")
Good catch.

2022-07-11 16:19 UTC, wwlwpd commented
When you address my comments in the commits and are ready for another review, please mark these mesh commits as "ready for review" so I know they are read. Thanks!

2022-07-11 17:10 UTC, jasonfleming commented
Will do. Haven't even run this mesh even once yet, so not sure how long it will be ...

2022-07-21 17:03 UTC, jasonfleming commented on config/mesh_defaults.sh
> +"uriv18"|"URIv18")
fixed this

2022-07-21 17:03 UTC, jasonfleming commented on config/mesh_defaults.sh
> +      INPUTDIR=$SCRIPTDIR/input/meshes/hsofs_NE-hires_v2_depf2
fixed this

2022-07-22 11:54 UTC, wwlwpd approved these changes
Will be merging manually after squash.

2022-07-22 11:57 UTC, closed without merging