Updated RMQ message to name correct wind product, confirmed asgs-msgr…
StormSurgeLive/asgs pull request #918
Opened 2022-07-12 17:56 UTC by notstarboard

This should address issue 884, where asgs-msgr.sh and asgs-msgr.py both use /usr/bin/python, which is the system python 2 (at least on hatteras). Now it will use python3, which should always be the ASGS python 3 when run via asgsh.

I also snuck in a change to an RMQ message in downloadGFS.sh that was confusing me for a bit in the console output. Now it should rightly print "GFS" when downloading GFS data instead of "NAM".

---

I've run into no errors from any of these changes, but I should caveat this with the fact that I'm still struggling to get my ASGS instance working as expected. If these changes introduced problems, depending on how subtle, it could be harder for me to catch them at present.

2022-07-12 18:29 UTC, wwlwpd commented on monitoring/asgs-msgr.sh
> +RMQMessaging_Python=$(which python3); # should be using python provided by ASGS environment
this should just be,

```
RMQMessaging_Python=python3
```

Because this is already available via `asgsh`'s `PATH` environmental variable.

2022-07-12 18:32 UTC, wwlwpd requested changes
Thanks for the PR!! I'd like to treat this PR as one that "gets RMQ" working in ASGS with `python3` - which is different than how we normally treat things. However since it's currently broken I don't want there to be incremental changes that don't get it fully working again. I can help with changing the bits that install the required modules during `./init-asgs.sh` (or after); but assuming the modules are installed this just needs to be able to work as before. Let me know clarification is needed. Thanks, again!

2022-07-21 18:22 UTC, wwlwpd commented
I moved this to draft so that it's easier to check the status in the PR list. When ready pls mark it "Ready for Review". Thanks!

2022-07-25 19:59 UTC, notstarboard commented
> I moved this to draft so that it's easier to check the status in the PR list. When ready pls mark it "Ready for Review". Thanks!

Apologies, I made the change but I didn't know to mark it ready for review! Should be all set.

2022-07-25 20:37 UTC, wwlwpd approved these changes
Looks good to me. I will take care of squashing these 3 commits into 1.

2022-07-25 20:45 UTC, closed without merging