Fixed python3 existence check
StormSurgeLive/asgs pull request #956
Opened 2022-07-26 20:25 UTC by notstarboard

2022-07-26 23:07 UTC, wwlwpd requested changes
see comment for requested change

2022-07-26 23:07 UTC, wwlwpd commented on monitoring/asgs-msgr.sh
> +if [[ ! -e $(command -v ${RMQMessaging_Python}) ]] ; then
I'd like use `which` here, mainly for consistency. But I also had to look up what `command -v` does, and it seems like `which` is what we want. 

But that does give me an idea for a `better` command that acts like `which` so I can say, "`which` is `better`" without it being a question. xD

... on second thought, change it also to use `-x` and wrap it in quotes, though it'd be strange for a platform to not have `python3` these days:

```
 if [[ ! -x "$(which ${RMQMessaging_Python})" ]] ; then 
```

This is untested, please make sure it works before you update the PR. Thanks!

2022-07-27 19:55 UTC, notstarboard commented
which and -x seem to work just fine!

2022-07-27 21:05 UTC, wwlwpd approved these changes
Looks good to me!

2022-07-27 21:06 UTC, wwlwpd commented
I approved it  but will merge it later since it has to be squashed.

2022-07-28 04:20 UTC, wwlwpd commented
merged this with a `cherry-pick` externally due to _squash_

2022-07-28 04:20 UTC, closed without merging